SELECT C.NAME AS "Ім'я", C.SURNAME AS "Прізвище", C.Phone AS "Телефон", COUNT(O.CLIENTID) AS "Кількість замовлень"
FROM CLIENTS C
JOIN ORDERS O ON O.CLIENTID = C.ID
WHERE C.ID IN (
  SELECT CLIENTID
  FROM ORDERS
  GROUP BY CLIENTID
  HAVING COUNT(CLIENTID) > 1
)
GROUP BY C.NAME, C.SURNAME, C.Phone;