
USE BOXES
SELECT C.NAME "Ім'я",C.SURNAME "Прізвище",C.PHONE "Телефон",SUM(O.SUM) "Сума замовлень"
FROM CLIENTS C JOIN ORDERS O on O.CLIENTID=C.ID
GROUP BY C.NAME,C.SURNAME,C.PHONE
GO
UPDATE CLIENTS 
SET REGULAR = 1
WHERE ID IN (
  SELECT C.ID
  FROM CLIENTS C 
  JOIN (
    SELECT CLIENTID, SUM(SUM) AS total_sum
    FROM ORDERS
    GROUP BY CLIENTID
    HAVING SUM(SUM) > 20000
  ) O ON O.CLIENTID = C.ID
);